### ISSUE TITLE
Tooot constantly crashes on Friendica

### ISSUE THREAD

**Issue by annando** [tooot-app/app#147]
Recently Friendica has added a Mastodon compatible API. Most applications do work: https://github.com/friendica/friendica/blob/2021.06-rc/doc/API-Mastodon.md

Registering with Tooot does work and the first few posts are loaded. But at some point the app crashes and restarting the app can lead in either an immediate crash or a crash in a few seconds again.

I'm most likely sure that we do send stuff that Tooot doesn't like, question is only what.

These are some of the accesses that the app did:
```
127.0.0.1 - - [11/Jun/2021:17:56:33 +0000] "GET /api/v1/accounts/verify_credentials HTTP/1.1" 200 6322 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:56:34 +0000] "GET /api/v1/filters HTTP/1.1" 200 514 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:56:34 +0000] "GET /api/v1/preferences HTTP/1.1" 200 682 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:56:34 +0000] "GET /api/v1/timelines/public HTTP/1.1" 200 11150 "-" "tooot/2.0.4"
```

```
127.0.0.1 - - [11/Jun/2021:17:49:07 +0000] "GET /api/v1/accounts/verify_credentials HTTP/1.1" 200 6290 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:49:07 +0000] "GET /api/v1/lists HTTP/1.1" 200 930 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:49:08 +0000] "GET /api/v1/announcements?with_dismissed=true HTTP/1.1" 200 4912 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:49:08 +0000] "GET /api/v1/preferences HTTP/1.1" 200 5080 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:49:08 +0000] "GET /api/v1/filters HTTP/1.1" 200 4912 "-" "tooot/2.0.4"
127.0.0.1 - - [11/Jun/2021:17:49:15 +0000] "GET /api/v1/timelines/home HTTP/1.1" 200 49972 "-" "tooot/2.0.4"
```

I tested with both Android and iOS.

**Comment by xmflsct** [comment]
@annando Thanks for flagging! It is probably a corner case bug in tooot. I see crash logs for your instance at `*.ca`, which links to React Native's strict rule on wrapping text inside `<Text>`.

This happens when I write like:
```
status.something && <Component />
```
In certain cases when `status.something` becomes a text string being used instead of `<Component />` then throws the error.

I rewrite all above cases into proper format and released `v2.0.5`. It is an OTA so your app installation should receive it automatically. The next time you open the app, it should be on the latest version, you can check this in the settings.
Let me know if this version fixes the crash, and if not, could you provide a demo account so that I can debug further? Thanks!

**Comment by annando** [comment]
Thanks for this really fast reaction! I just updated my instance squeet.me to the latest version, you could create an account there.

We try to be as compatible as possible, so if anything needs to be changed from our side, please tell.

**Comment by xmflsct** [comment]
@annando Thanks. I registered an account, but could not login successfully. 
Get `/api/v1/preferences` gives `500` error.

After I manually bypass getting preferences, `/api/v1/timelines/public` hangs without response. Getting `/api/v1/timelines/home` is fine. Can you check why `/public` hangs? Hopefully I can debug further when `/public` is working.

**Comment by annando** [comment]
Thanks for the hint. I see it in the logs. At first I will fix the the 500 issue. I can imagine that there is some performance issue with the public timeline, I will have a look there next.

**Comment by xmflsct** [comment]
@annando Awesome! The public timeline is working fine without crashes. Though I notice 2 other issues (not a throughout test, just found out by coincidence).

Request `/api/v1/accounts/xxx` returns empty avatar.
Also, the `timelines` endpoint does not return `Link` header which tooot uses for pagination, guess probably for other clients also. Therefore currently tooot can only display 1 page due to this.

**Comment by annando** [comment]
Thanks for having a deeper look! Concerning the link header: Yeah, I hadn't implemented it yet because I wasn't sure if that had been used at all. So it's now on my list.

**Comment by xmflsct** [comment]
@annando Great! Are you still experiencing crashes on `v2.0.5`? If not, I will close this ticket and feel free to open new ones if you spot anything!

**Comment by annando** [comment]
It seems to work now, thanks very much!

**Comment by xmflsct** [comment]
@annando Good luck with building the api!

**Comment by annando** [comment]
A small update: I now implemented the `Link` header as well - and it seem to work fine with Tooot. Thanks for the hint for this. Otherwise I most likely had ignored it.

**Comment by xmflsct** [comment]
@annando Thanks for the update!

The reason why `Link` header is used is because, for Mastodon instances, notification list and few other lists, message id is not the same as the id for pagination purpose.. I don't know why..
