### ISSUE TITLE
Add moderation

### ISSUE THREAD

**Issue by MaybeThisIsRu** [tooot-app/app#237]
Some basics would be nice to start.

- Suspend/limit a user. 
- Refresh a user's profile.
- See reports submitted by users.

**Comment by xmflsct** [comment]
Regarding your questions:

- As a user, you can already hide/block/report etc. about another user
- It is a bit tricky to achieve, the best way is to navigate away and back that will refetch a user's profile
- I assume this is an admin action? If so, that is not in the scope of tooot unfortunately

**Comment by MaybeThisIsRu** [comment]
> It is a bit tricky to achieve, the best way is to navigate away and back that will refetch a user's profile

Instance admins are able to fetch remote profiles manually. This causes a hard refresh of what's available locally on our own instance.

> I assume this is an admin action? If so, that is not in the scope of tooot unfortunately

That is unfortunate...

**Comment by xmflsct** [comment]
> Sorry, I meant to say block/suspend/limit another instance

Yes users can report another instance, but for admins to actually take action, that has to be done on the web interface.

The reason is simply that, majority of the users of tooot are not admins.

Though I do want to make it easier to open up web interface easier. Still figuring out how to achieve that.

**Comment by xmflsct** [comment]
Fixed in v3.5.4
