### ISSUE TITLE
Pleroma login doesn’t work

### ISSUE THREAD

**Issue by icyphox** [tooot-app/app#238]
Hi, I’m unable to login using Pleroma. As I understand it, the OAuth process should be identical to Mastodon’s. Here’s what happens when I try:
- I enter my instance URL and hit login
- Get prompted to authorise the app via the browser 
- Input credentials and hit login
- Comes back to the app, but I haven’t logged in. Still in the instance page.

**Comment by xmflsct** [comment]
Unfortunately many of the APIs from Mastodon are returned with not implemented by Pleroma, therefore the login process terminates, because some of the API calls failed.

I wanted to support such as Pleroma through using external libraries such as this one, https://github.com/tooot-app/app/issues/29, but due to React Native limitations, it is not that straightforward of implementing that library.
