### ISSUE TITLE
Language filter

### ISSUE THREAD

**Issue by limdingwen** [tooot-app/app#409]
Hi! I have a request (might contribute to app myself if I can find out how to do it for iOS...). Is there a way to filter toots by languages in the app?

**Comment by xmflsct** [comment]
There are multiple perspectives to answer your question.

Firstly, yes each toot's metadata has a language field indicating the language this toot is in. However, such detection was mostly relying on each instance/server and was not accurate in most of the cases. In the most recent version, such detection has even been removed, therefore in the web UI, you would see a language option when posting toot.

Secondly, you can customise your experience of your instance, see https://docs.joinmastodon.org/user/preferences/, the last section. I think this setting affects the API response as well but I am not 100% sure. Again, in order to achieve this functionality, Mastodon has to rely on the language detection mentioned above which is known to be inacurate.

Last but not least, tooot offers translation when it detects a toot's language differs from your app's language. How does it work? Well, I used to rely on the server detection as mentioned above, but recently I have switched to use OS's built in language detection functionality, which is much more accurate than server detection, and Android's is better iOS's unfortunately. :-) So now whenever you open a toot in tooot, the app detects the language locally then decide if would offer a translation option.

So to conclude, yes it is possible to achieve this functionality locally in the app, but I would doubt how efficient it is as we have to ask the OS to do language detection on ALL the toots you are just scrolling through which is probably not battery friendly either.
