### ISSUE TITLE
Show extended account info when viewing account from foreign server

### ISSUE THREAD

**Issue by SteveDinn** [tooot-app/app#457]
When I'm viewing an account from a server that is not the one I've authenticated to, I would like to have a link to view the account on its originating server.

Alternatively, the app could load the extended information such as older toots, followed accounts, and following accounts from the originating server and present it on the account view. 

**Use case:** An account on a foreign server followed mine and I clicked on the notification. I was shown the account, but no extended information about it. This information could help me decide whether or not to follow it back.

**Comment by SteveDinn** [comment]
For example, I just followed an account from a foreign server and I can see that it has 75 followed accounts, but I only see myself, presumably because they aren't cached by my server yet.

![Screenshot_20221112-153718](https://user-images.githubusercontent.com/3911507/201491657-4db15090-9d6c-406d-a9cb-4617c2e75800.png)

**Comment by xmflsct** [comment]
Yes I can add a link to open the profile on the original server in the browser.

However retrieving an account's details on a foreign server is not possible technically. In order to retrive an account's information, one has to know the account ID on the server it is requesting. There is no way to search or get such ID from the Mastodon instance you are authenticated to. Maybe such ID is stored somewhere by Mastodon but at least it is not exposed through the API.

**Comment by stom79** [comment]
Hey there. I am the dev of Fedilab and we have been pinged on that issue since we added that feature. 

Mastodon allows searches without authentication (but turn off resolve and pagination in your api call).
So, by searching a user in their own instance you will get their ID on it. Then you can display their public timelines.
