### ISSUE TITLE
single tap to boost

### ISSUE THREAD

**Issue by leonschreuder** [tooot-app/app#482]
I love this app, and you've done amazing work, but there is one thing that is kind of a usability deal breaker for me and that is that I have to navigate a menu every time i want to boost a post. I get that it is the most similar to the twitter UI but i think it's really more of a nuisance for anyone there as well, and neither the web UI nor any of the other apps I've tried have the option to do an unlisted boost.

I've tried to search for a setting to disable it, I've tried to search for an issue explaining why it was be implemented this way but I came up empty. So i guess then this is a feature request to make boosting single-tap, either per default, or per a settings entry.

**Comment by xmflsct** [comment]
So, I understand this is a very much personal preference matter. The boost menu is **not** about following what Twitter does. In fact, the goal is different, just that how it works turned out to be the same.

This is the issue and related commit: https://github.com/tooot-app/app/issues/427. And you can see the linked issue in there is more than one year old. There has been careful consideration of this implementation. And yes, I can provide an option in the app, but I do not want to blow up the app with hundreds of settings which at the end most users would struggle with that many options.
