### ISSUE TITLE
An updated version on the server side

### ISSUE THREAD

**Issue by jimmyorz** [tooot-app/app#595]
![image](https://user-images.githubusercontent.com/66128107/208791465-41669ef5-812c-4f56-ace9-3b5644ccf805.jpeg)
Should be 4.7.1 now?

![image](https://user-images.githubusercontent.com/66128107/208791706-430fc2d6-4350-458f-bc79-41939b63d149.jpeg)
This causes the update red dot on the App to not disappear

**Comment by xmflsct** [comment]
No no, this has nothing to do with the version mentioned in package.json. The app fetches the latest version from `https://tooot.app/version.json`. Since I am migrating the website from Vercel to Cloudflare Pages today, DNS is still being updated so most likely you would see 4.7.0 in there, but in some hours it should show 4.7.1.

I thought this commit should have fixed the problem https://github.com/tooot-app/app/commit/4bd11e22461fbfbaf5da3820f05d4ae8b3ab2692. Maybe I shall just make it less aggressive. It was implemented when I had 2 update channels, one for updating native codes (requires full app update), and another one for updating purely the JS on the fly. Updating JS channel has since been removed as Expo starts charging for it. And I may not need to nudge users to update anymore as for every update now, native code change can be done if needed.

**Comment by jimmyorz** [comment]
Thank you for your detailed explanation!

The json on my side does show 4.7.1, but the App still shows the update red dot.
This is the same on all three of my devices.
I will watch for a while.

Happy holidays!

**Comment by xmflsct** [comment]
I think I might just remove this check altogether 🙈
